language: python
python: 3.4
install:
  - pip install -r requirements/tox.txt
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coverage combine
  - coverage report
  - coveralls
