before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y 'libsdl2-2.*' 'libsdl2-gfx-1.*' 'libsdl2-ttf-2.*'
language: python
python: 3.4
install:
  - pip install -r requirements/tox.txt
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coverage combine
  - coverage report
  - coveralls
